# ==================================================
# = API GATEWAY - CONFIGURATION EXAMPLE
# ==================================================

spring.application.name=apigateway

# ==================================================
# = REDIS (UPSTASH)
# ==================================================
# Se obtiene desde variable de entorno REDIS_URL

spring.data.redis.url=${REDIS_URL}